CREATE TABLE "BENUTZER" ("UID" INTEGER PRIMARY KEY  NOT NULL ,
"NAME" VARCHAR(255) NOT NULL ,
"PWD" VARCHAR(255),
"ACTIVE" BOOLEAN NOT NULL DEFAULT 1);

INSERT INTO "BENUTZER" (NAME, PWD, ACTIVE) 
VALUES ("ADMINISTRATOR", "63a9f0ea7bb98050796b649e85481845", 1);

ALTER TABLE "BEWERBUNGEN"
ADD UID INTEGER REFERENCES BENUTZER(UID);

UPDATE BEWERBUNGEN SET UID = 1;
