CREATE TABLE "COMPANIES" ("ID" INTEGER PRIMARY KEY  NOT NULL ,"NAME" VARCHAR(255) NOT NULL ,"NOTES" VARCHAR(8000),"VERMITTLER" BOOLEAN NOT NULL  DEFAULT (0),"AKTIV" BOOLEAN NOT NULL  DEFAULT (-1));

ALTER TABLE "BEWERBUNGEN" ADD COMPANY INTEGER;

DROP VIEW V_COMPANIES;
CREATE VIEW "V_COMPANIES" AS SELECT DISTINCT ID, NAME VALUE, VERMITTLER FROM COMPANIES ORDER BY NAME;

INSERT INTO COMPANIES(NAME, VERMITTLER)
SELECT DISTINCT NAME, VERMITTLER FROM BEWERBUNGEN;

UPDATE BEWERBUNGEN
SET COMPANY = (SELECT ID FROM COMPANIES WHERE NAME = BEWERBUNGEN.NAME);

CREATE TEMPORARY TABLE t1_backup(
	`ID`	INTEGER NOT NULL,
	`DATUM`	DATETIME NOT NULL,
	`MAIL`	VARCHAR(255),
	`JOBTITEL`	VARCHAR(255) NOT NULL,
	`REFNR`	VARCHAR(255),
	`TYP`	INT NOT NULL,
	`FEEDBACK`	INT NOT NULL,
	`RESULT`	INT NOT NULL,
	`WVL`	DATETIME NOT NULL,
	`NOTES`	VARCHAR(8000),
	`VERMITTLER`	BOOLEAN NOT NULL DEFAULT (0),
	`MEDIUM`	INTEGER NOT NULL DEFAULT (0),
	`ANSPRECHPARTNER`	VARCHAR(255),
	`BEFRISTET`	BOOLEAN NOT NULL DEFAULT (0),
	`IGNORIERT`	BOOLEAN NOT NULL DEFAULT (0),
	`UID`	INTEGER,
	`BISDATUM`	DATETIME,
	`COMPANY`	INTEGER,
	PRIMARY KEY(ID),
	FOREIGN KEY(`UID`) REFERENCES BENUTZER ( UID ));
INSERT INTO t1_backup SELECT 	`ID`,
	`DATUM`,
	`MAIL`,
	`JOBTITEL`,
	`REFNR`,
	`TYP`,
	`FEEDBACK`,
	`RESULT`,
	`WVL`,
	`NOTES`,
	`VERMITTLER`,
	`MEDIUM`,
	`ANSPRECHPARTNER`,
	`BEFRISTET`,
	`IGNORIERT`,
	`UID`,
	`BISDATUM`,
	`COMPANY` FROM BEWERBUNGEN;
DROP TABLE BEWERBUNGEN;
CREATE TABLE `BEWERBUNGEN` (
	`ID`	INTEGER NOT NULL,
	`DATUM`	DATETIME NOT NULL,
	`MAIL`	VARCHAR(255),
	`JOBTITEL`	VARCHAR(255) NOT NULL,
	`REFNR`	VARCHAR(255),
	`TYP`	INT NOT NULL,
	`FEEDBACK`	INT NOT NULL,
	`RESULT`	INT NOT NULL,
	`WVL`	DATETIME NOT NULL,
	`NOTES`	VARCHAR(8000),
	`VERMITTLER`	BOOLEAN NOT NULL DEFAULT (0),
	`MEDIUM`	INTEGER NOT NULL DEFAULT (0),
	`ANSPRECHPARTNER`	VARCHAR(255),
	`BEFRISTET`	BOOLEAN NOT NULL DEFAULT (0),
	`IGNORIERT`	BOOLEAN NOT NULL DEFAULT (0),
	`UID`	INTEGER,
	`BISDATUM`	DATETIME,
	`COMPANY`	INTEGER NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY(`UID`) REFERENCES BENUTZER ( UID ),
	FOREIGN KEY(`COMPANY`) REFERENCES COMPANIES ( ID )
);
INSERT INTO BEWERBUNGEN SELECT `ID`,
	`DATUM`,
	`MAIL`,
	`JOBTITEL`,
	`REFNR`,
	`TYP`,
	`FEEDBACK`,
	`RESULT`,
	`WVL`,
	`NOTES`,
	`VERMITTLER`,
	`MEDIUM`,
	`ANSPRECHPARTNER`,
	`BEFRISTET`,
	`IGNORIERT`,
	`UID`,
	`BISDATUM`,
	`COMPANY`  FROM t1_backup;
DROP TABLE t1_backup;
