CREATE TABLE JOBS("ID" INTEGER PRIMARY KEY  NOT NULL ,"NAME" VARCHAR(255) NOT NULL);

ALTER TABLE "BEWERBUNGEN" ADD JOB INTEGER;

DROP VIEW V_JOBS;
CREATE VIEW "V_JOBS" AS SELECT DISTINCT ID, NAME VALUE FROM JOBS ORDER BY NAME;

INSERT INTO JOBS(NAME)
SELECT DISTINCT JOBTITEL FROM BEWERBUNGEN;

UPDATE BEWERBUNGEN
SET JOB = (SELECT ID FROM JOBS WHERE NAME = BEWERBUNGEN.JOBTITEL);

CREATE TEMPORARY TABLE t1_backup(
	`ID`	INTEGER NOT NULL,
	`DATUM`	DATETIME NOT NULL,
	`MAIL`	VARCHAR(255),
	`REFNR`	VARCHAR(255),
	`TYP`	INT NOT NULL,
	`FEEDBACK`	INT NOT NULL,
	`RESULT`	INT NOT NULL,
	`WVL`	DATETIME NOT NULL,
	`NOTES`	VARCHAR(8000),
	`VERMITTLER`	BOOLEAN NOT NULL DEFAULT (0),
	`MEDIUM`	INTEGER NOT NULL DEFAULT (0),
	`ANSPRECHPARTNER`	VARCHAR(255),
	`BEFRISTET`	BOOLEAN NOT NULL DEFAULT (0),
	`IGNORIERT`	BOOLEAN NOT NULL DEFAULT (0),
	`UID`	INTEGER,
	`BISDATUM`	DATETIME,
	`COMPANY`	INTEGER NOT NULL,
	`JOB` INTEGER NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY(`UID`) REFERENCES BENUTZER ( UID ));
INSERT INTO t1_backup SELECT 	`ID`,
	`DATUM`,
	`MAIL`,
	`REFNR`,
	`TYP`,
	`FEEDBACK`,
	`RESULT`,
	`WVL`,
	`NOTES`,
	`VERMITTLER`,
	`MEDIUM`,
	`ANSPRECHPARTNER`,
	`BEFRISTET`,
	`IGNORIERT`,
	`UID`,
	`BISDATUM`,
	`COMPANY`,
	`JOB` FROM BEWERBUNGEN;
DROP TABLE BEWERBUNGEN;
CREATE TABLE `BEWERBUNGEN` (
	`ID`	INTEGER NOT NULL,
	`DATUM`	DATETIME NOT NULL,
	`MAIL`	VARCHAR(255),
	`REFNR`	VARCHAR(255),
	`TYP`	INT NOT NULL,
	`FEEDBACK`	INT NOT NULL,
	`RESULT`	INT NOT NULL,
	`WVL`	DATETIME NOT NULL,
	`NOTES`	VARCHAR(8000),
	`VERMITTLER`	BOOLEAN NOT NULL DEFAULT (0),
	`MEDIUM`	INTEGER NOT NULL DEFAULT (0),
	`ANSPRECHPARTNER`	VARCHAR(255),
	`BEFRISTET`	BOOLEAN NOT NULL DEFAULT (0),
	`IGNORIERT`	BOOLEAN NOT NULL DEFAULT (0),
	`UID`	INTEGER,
	`BISDATUM`	DATETIME,
	`COMPANY`	INTEGER NOT NULL,
	`JOB` INTEGER NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY(`UID`) REFERENCES BENUTZER ( UID ),
	FOREIGN KEY(`COMPANY`) REFERENCES COMPANIES ( ID ),
	FOREIGN KEY(`JOB`) REFERENCES JOBS ( ID )
);
INSERT INTO BEWERBUNGEN SELECT `ID`,
	`DATUM`,
	`MAIL`,
	`REFNR`,
	`TYP`,
	`FEEDBACK`,
	`RESULT`,
	`WVL`,
	`NOTES`,
	`VERMITTLER`,
	`MEDIUM`,
	`ANSPRECHPARTNER`,
	`BEFRISTET`,
	`IGNORIERT`,
	`UID`,
	`BISDATUM`,
	`COMPANY`,
	`JOB`  FROM t1_backup;
DROP TABLE t1_backup;
