CREATE  TRIGGER  IF NOT EXISTS "main"."AI_BEWERBUNGEN" AFTER INSERT ON "BEWERBUNGEN" BEGIN INSERT INTO LOG(DATUM, BEWERBUNG, TYP, BESCHREIBUNG) 
SELECT NEW.DATUM, NEW.ID, "VERSAND", "BEWERBUNGSUNTERLAGEN VERSENDET"; END;

CREATE  TRIGGER  IF NOT EXISTS "main"."BD_BEWERBUNGEN" BEFORE DELETE ON "BEWERBUNGEN" BEGIN DELETE FROM DOCUMENTS WHERE BEWERBUNG = OLD.ID;
DELETE FROM LOG WHERE BEWERBUNG = OLD.ID; END;

ALTER TABLE COMPANIES ADD NOREACTION BOOLEAN NOT NULL  DEFAULT (0);
