ALTER TABLE BEWERBUNGEN ADD NoResponse BOOLEAN DEFAULT(0);
UPDATE BEWERBUNGEN SET NoResponse = -1 WHERE Result = 4 OR WVLSTUFE > 0;
UPDATE BEWERBUNGEN SET NoResponse = -1 WHERE (WVLSTUFE = 0) AND (date(WVL) < date('now')) AND (RESULT = 0);
UPDATE BEWERBUNGEN SET RESULT = 0 WHERE RESULT = 4;
