CREATE VIEW "V_EXPORT" AS
SELECT UID, DATUM, WVL, WVLSTUFE AS STUFE, BISDATUM, COMPANIES.NAME NAME, MAIL,
JOBS.NAME JOBTITEL, REFNR, (RESULT = 1) * -1 AS ZUSAGE,
(RESULT = 2) * -1 AS ABSAGE,
NoResponse AS KEINEANTWORT, COMPANIES.NOREACTION AS REAGIERTNICHT
FROM BEWERBUNGEN 
JOIN COMPANIES ON BEWERBUNGEN.COMPANY = COMPANIES.ID
JOIN JOBS ON BEWERBUNGEN.JOB = JOBS.ID;
