CREATE TABLE "BEWERBUNGEN" ("ID" INTEGER PRIMARY KEY  NOT NULL ,"DATUM" DATETIME NOT NULL ,"NAME" VARCHAR(255) NOT NULL ,"MAIL" VARCHAR(255),"JOBTITEL" VARCHAR(255) NOT NULL ,"REFNR" VARCHAR(255),"TYP" INT NOT NULL ,"FEEDBACK" INT NOT NULL ,"RESULT" INT NOT NULL ,"WVL" DATETIME NOT NULL ,"NOTES" VARCHAR(8000),"VERMITTLER" BOOLEAN NOT NULL  DEFAULT (0) ,"MEDIUM" INTEGER NOT NULL  DEFAULT (0) ,"ANSPRECHPARTNER" VARCHAR(255), "BEFRISTET" BOOLEAN NOT NULL  DEFAULT 0, "IGNORIERT" BOOLEAN NOT NULL  DEFAULT 0);
CREATE TABLE "DOCUMENTS" ("ID" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL , "TYPE" VARCHAR NOT NULL , "FILENAME" VARCHAR NOT NULL  UNIQUE , "BEWERBUNG" INTEGER NOT NULL REFERENCES BEWERBUNG(ID) );
CREATE TABLE "LOG"(
ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
DATUM DATETIME NOT NULL,
BEWERBUNG INT NOT NULL REFERENCES BEWERBUNGEN(ID),
TYP VARCHAR(255) NOT NULL,
BESCHREIBUNG VARCHAR(8000));
CREATE VIEW "V_COMPANIES" AS     select distinct name VALUE from bewerbungen order by name;
CREATE VIEW "V_JOBS" AS   select distinct jobtitel VALUE from bewerbungen order by jobtitel;
CREATE VIEW "V_MAILS" AS   select distinct mail VALUE from bewerbungen where not (mail is null) order by mail;
CREATE VIEW "V_RECEIPENTS" AS select distinct ansprechpartner VALUE from bewerbungen order by ansprechpartner;
CREATE TRIGGER "AI_BEWERBUNGEN" AFTER INSERT ON "BEWERBUNGEN" BEGIN  INSERT INTO LOG(DATUM, BEWERBUNG, TYP, BESCHREIBUNG)
SELECT NEW.DATUM, NEW.ID, "VERSAND", "BEWERBUNGSUNTERLAGEN VERSENDET"; END;
CREATE UNIQUE INDEX "IX_DOCUMENTS" ON "DOCUMENTS" ("TYPE" ASC, "FILENAME" ASC);
